# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdetail',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后更新日期'),
        ),
        migrations.AlterField(
            model_name='assetdetail',
            name='scrap_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='报废日期'),
        ),
    ]
