# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 06:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qusetions',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 24, 6, 22, 48, 567907, tzinfo=utc)),
        ),
    ]
