# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160924_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qusetions',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
